version: "3"
services:
  reverseproxy:
      image: bjoebstl/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: bjoebstl/udacity-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: DEV_POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: DEV_POSTGRESS_PASSWORD 
      POSTGRESS_DB: DEV_POSTGRESS_DATABASE
      POSTGRESS_HOST: DEV_POSTGRESS_HOST 
      AWS_REGION: DEV_AWS_REGION 
      AWS_PROFILE: DEV_AWS_PROFILE 
      AWS_BUCKET: DEV_AWS_MEDIA_BUCKET
      JWT_SECRET: JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: bjoebstl/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: DEV_POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: DEV_POSTGRESS_PASSWORD 
      POSTGRESS_DB: DEV_POSTGRESS_DATABASE
      POSTGRESS_HOST: DEV_POSTGRESS_HOST 
      AWS_REGION: DEV_AWS_REGION 
      AWS_PROFILE: DEV_AWS_PROFILE 
      AWS_BUCKET: DEV_AWS_MEDIA_BUCKET
      JWT_SECRET: JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: bjoebstl/udacity-frontend:local
    ports:
      - "8100:80"