version: "1"
services:
  reverseproxy:
    build:
      context: .
    image: bjoebstl/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: bjoebstl/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: bjoebstl/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: bjoebstl/udacity-frontend:local